name: Backend CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code # 저장소에 있는 코드 가져오기
        uses: actions/checkout@v4

      - name: Set up JDK 17 # JDK 설치
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle # Gradle 설정, 종속성 및 빌드 캐시를 자동으로 관리
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          cache-read-only: false # 캐시 읽기 및 쓰기 활성화

      - name: Grant Execute Permission For Gradlew # Gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: Build with Gradle # Gradle 빌드 실행
        run: | # 실패 즉시 중단
          set -e
          ./gradlew clean build

      - name: Test with Gradle # 테스트 실행
        run: |
          set -e
          ./gradlew test
